//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hmt.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Admin
    {
        public int admin_id { get; set; }

        [DisplayName("Password")]
        [Required(ErrorMessage = "Password is required")]
        [DataType(DataType.Password)]
        public string admin_password { get; set; }


        [DisplayName("First Name")]
        public string admin_fname { get; set; }

        [DisplayName("Last Name")]
        public string admin_lname { get; set; }

        [DisplayName("Email")]
        public string admin_email { get; set; }

        [DisplayName("Username")]
        [Required(ErrorMessage = "Username is required")]
        public string admin_username { get; set; }
    }
}
