//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hmt.Models

{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Requests = new HashSet<Request>();
        }

        public int emp_id { get; set; }

        [DisplayName("First Name")]
        public string emp_fname { get; set; }

        [DisplayName("Last Name")]
        public string emp_lname { get; set; }

        [DisplayName("Username")]
        [Required(ErrorMessage = "Username is required")]
        public string emp_username { get; set; }


        [DisplayName("Password")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Password is required")]

        public string emp_password { get; set; }

        [DisplayName("Designation")]
        public string emp_designation { get; set; }

        [DisplayName("Email")]

        public string emp_email { get; set; }

        [DisplayName("City")]
        public string emp_city { get; set; }

        [DisplayName("Country")]
        public string emp_country { get; set; }

        [DisplayName("Gender")]
        public string emp_gender { get; set; }

        [DisplayName("Qualification")]
        public string emp_qualification { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Requests { get; set; }
    }
}
