//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hmt.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Request
    {
        [DisplayName("Id")]
        public int req_id { get; set; }

        [DisplayName("Status")]
        public string req_status { get; set; }

        [DisplayName("Amount")]
        public int req_amount { get; set; }

        [DisplayName("Date/Time")]
        public System.DateTime req_date { get; set; }

        [DisplayName("Employee id")]
        public int emp_id { get; set; }

        [DisplayName("Product id")]
        public int pro_id { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Stationary Stationary { get; set; }
    }
}
