//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hmt.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;
    using System.ComponentModel.DataAnnotations;
    public partial class Stationary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stationary()
        {
            this.Requests = new HashSet<Request>();
        }
    
        public int pro_id { get; set; }

        [DisplayName("Name")]
        [Required(ErrorMessage = "Enter Product Name")]
        public string pro_name { get; set; }

        [Required(ErrorMessage = "Enter Product Image")]
        [DisplayName("Image")]
        public string pro_image { get; set; }

        [Required(ErrorMessage = "Enter Product Description")]
        [DisplayName("Description")]
        public string pro_description { get; set; }

        [Required(ErrorMessage = "Enter Product Price")]
        [DisplayName("Price")]
        public int pro_price { get; set; }

        [DisplayName("Stock")]
        public int pro_stock { get; set; }

        [DisplayName("Category id")]
        public int cat_id { get; set; }


        public HttpPostedFileBase ImageFile { get; set; }

        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Requests { get; set; }
    }
}
